#!/bin/bash
current_windows=$(xdotool search --class konsole | xargs -I sw xdotool getwindowname sw | sort -u)

if [ -z "$current_windows" ]; then
	konsole &
	exit
fi
	
active_window=$(xdotool getwindowfocus getwindowname | awk 'NF>1{print $NF}')

[[ "$active_window" = "Konsole" ]] && xdotool key super+Down && exit

# will not work at all with multiple windows
window_location=$(wmctrl -l | grep Konsole | awk '{print $1}' | head -1)
wmctrl -i -r $window_location -t -1	
xdotool search --class konsole | xargs -I sw xdotool windowactivate sw
