#!/bin/bash


if [ ! -d "$HOME/.oh-my-zsh" ]; then
	echo "installing oh-my-zsh"
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi

echo "undoing the default .zshrc change"
yadm checkout .zshrc
