#!/bin/bash

source $HOME/scripts/programs.sh

# this needs to be absolutely last because it won't respect &
if [ ! -d "$HOME/.oh-my-zsh" ]; then
	echo "installing oh-my-zsh"
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" &
	echo "undoing the default .zshrc change"
	yadm checkout .zshrc
fi

